version: '3'

services:
  frontend:
    build:
      context: .
    ports:
      - "80:80"
      - "8443:443"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx_custom_config:/etc/nginx/sites-available/default
      - /etc/nginx/ssl
    ports:
      - "80:80"
      - "8443:443"
